M48
; DRILL file {KiCad 9.0.1} date 2026-09-25T23:59:16+0300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-25T23:59:16+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.660
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.100
%
G90
G05
T1
X95.714Y-68.22
X95.714Y-74.0
T2
X90.56Y-43.7
X90.56Y-46.24
M30
